# Generated by Django 4.2.27 on 2025-12-11 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('parsed_skills', models.JSONField(blank=True, default=list)),
                ('parsed_experience', models.CharField(blank=True, max_length=100)),
                ('parsed_education', models.CharField(blank=True, max_length=200)),
                ('parsed_email', models.EmailField(blank=True, max_length=254)),
                ('parsed_phone', models.CharField(blank=True, max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Matching score 0-100')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Application status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'applied_at'], name='application_status_89c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'),
        ),
    ]
